#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /r
  controller: App\Controller\RetailCRMCreateTestWorkINeedDoItController::index
rarusha:
  path: /rr
  controller: App\Controller\RetailCRMCreateTestWorkINeedDoItController::ordersR